BASEURL = "https://pokeapi.co/api/v2/"
COLOSSEUM_MONS = [
    "espeon", "umbreon",
    "makuhita", "hariyama",
    "bayleef", "meganium",
    "quilava", "typhlosion",
    "croconaw", "feraligatr",
    "misdreavus", 
    "slugma", "magcargo",
    "noctowl",
    "flaafy", "ampharos",
    "skiploom", "jumpluff",
    "quagsire",
    "furret",
    "yanma",
    "remoraid", "octillery",
    "mantine",
    "quilfish",
    "dunsparce",
    "meditite", "medicham",
    "swablu", "altaria",
    "sudowoodo",
    "plusle",
    "hitmontop",
    "entei",
    "ledian",
    "suicune",
    "gligar",
    "sneasel",
    "piloswine",
    "stantler",
    "ariados",
    "aipom",
    "murkrow",
    "forretress",
    "granbull",
    "vibrava",
    "raikou",
    "sunflora",
    "delibird",
    "heracross",
    "skarmory",
    "miltank",
    "absol",
    "houndoom",
    "tropius",
    "metagross",
    "tyranitar",
    "smeargle",
    "ursaring",
    "shuckle",
    "togetic",
    "ho-oh"
]
XD_MONS = [
        "eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon",
        "teddiursa", "ursaring",
        "ledyba", "ledian",
        "poochyena", "mightyena",
        "houndour", "houndoom",
        "baltoy", "claydol",
        "spheal", "sealeo", "walrein",
        "mareep", "flaafy", "ampharos",
        "gulpin", "swalot",
        "seedot", "nuzleaf", "shiftry",
        "spinarak", "ariados",
        "numel", "camerupt",
        "shroomish", "breloom",
        "carvanha", "sharpedo",
        "delcatty",
        "voltorb", "electrode",
        "makuhita", "hariyama",
        "vulpix", "ninetales",
        "duskull", "dusclops",
        "ralts", "kirlia", "gardevoir",
        "mawile",
        "snorunt", "glalie",
        "natu", "xatu",
        "roselia",
        "meowth", "persian",
        "swinub", "piloswine",
        "spearow", "fearow",
        "grimer", "muk",
        "seel", "dewgong",
        "lunatone",
        "nosepass",
        "zangoose",
        "paras", "parasect",
        "growlithe", "arcanine",
        "shellder", "cloyster",
        "beedrill",
        "pidgeotto", "pidgeot",
        "tangela",
        "butterfree",
        "magneton",
        "venomoth",
        "weepinbell",
        "arbok",
        "primape",
        "hypno",
        "golduck",
        "sableye",
        "dodrio",
        "raticate",
        "farfetchd",
        "altaria",
        "kangaskhan",
        "banette",
        "magmar",
        "pinsir",
        "rapidash",
        "magcargo",
        "hitmonchan",
        "hitmonlee",
        "lickitung",
        "scyther",
        "chansey", "blissey",
        "solrock",
        "starmie",
        "swellow",
        "electabuzz",
        "snorlax",
        "poliwrath",
        "mr-mime",
        "dugtrio",
        "manectric",
        "salamence",
        "marowak",
        "lapras",
        "rhydon",
        "exeggutor",
        "tauros",
        "dragonite",
        "lugia",
        "articuno",
        "zapdos",
        "moltres",
        "togepi", "togetic",
        "hoppip", "skiploom", "jumpluff",
        "phanpy", "donphan",
        "surskit", "masquerain",
        "zubat", "golbat", "crobat",
        "aron", "lairon", "aggron",
        "wooper", "quagsire",
        "sandshrew", "sandslash",
        "gligar",
        "trapinch", "vibrava", "flygon",
        "chikorita", "bayleef", "meganium",
        "cyndaquil", "Quilava", "typhlosion",
        "totodile", "croconaw", "feraligatr",
        "elekid",
        "meditite", "medicham",
        "shuckle",
        "larvitar", "pupitar", "tyranitar"
    ]